### ISSUE TITLE
Support Updating of Slug

### ISSUE THREAD

**Issue by allenwyma** [ash-project/ash_slug#28]
**Is your feature request related to a problem? Please describe.**
When a value is updated, the slug doesn't seem to update.

**Describe the solution you'd like**
The function should apply whenever the value has been updated.

It'd also be nice to have a "callback" where we can keep track of the last value, and we can say insert that into a table and redirect old slugs to the new slug for bookmarked pages, etc.

**Describe alternatives you've considered**
This may be possible to be done as is, but I htink having this in the DSL, would be better to have as it's more clear and realted to ash_slug.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

Existing:

```elixir
  actions do
    update :update do
      change slugify(:name, into: :slug)
    end
  end
```

To

```elixir
 ash_slug do
  slugify(:name, into: slug), on: [:create, :update] do
     change fn changeset ->
     # do what you want with the old value, etc.
     end
  end
 end
```

**Additional context**

**Comment by rhblind** [comment]
Hello,
Sorry for late response on this issue. I can't seem to reproduce your issue, and have [pushed a test-case](https://github.com/ash-project/ash_slug/commit/23bb91fade7eae5f2b58fd2c38125b989872e661) that should cover it.

For your second suggestion, you can always just use a regular `change` to get access to your changeset and then apply the `slugify` change function directly from within that.

```elixir
defmodule MyResource do 
  use Ash.Resource,
    extensions: [AshSlug]

  attributes do 
    attribute text, :string, public?: true
  end
  
  actions do 
    create :create do 
      accept [:text]

      change slugify(:text, lowercase?: false)
    end

    update :update do 
      require_atomic? false
      accept [:text]

      change fn changeset, context do
        # Do something with your changeset
        AshSlug.Changes.Slugify.change(changeset, [attribute: :text1, into: :text1, lowercase: false], context)
      end
    end
  end
end
```

The only caveat is that since some options are provided by default when calling slugify the "normal" way, you'll have to provide them when calling manually.
Also note that the `lowercase?` option is aliased for `lowercase` to semantically fit better within the Ash ecosystem, but when calling manuall, you'll have to use the `lowercase` (without question mark) variant.

Ash for expanding the DSL, I don't think we want to go there. I discussed a similar approach with Zach when writing this little extension, and we settled that this functionality is "too simple" to justify a separate `ash_slug do .. end` block in resources. We really want to keep it as a simple `change` extension.

**Comment by allenwyma** [comment]
Thanks, will use this on my side.
